version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - MODEL_PATH=./model/yolov8x.pt
      - DEVICE=cpu
      - HOST=0.0.0.0
      - PORT=5000
      - CONF=0.4
      - CENTER_PERCENTAGE_X=0.5
      - CENTER_PERCENTAGE_Y=0.7
      - MASKS_PATH=./data/masks/
      # - NVIDIA_VISIBLE_DEVICES= all
      # - NVIDIA_DRIVER_CAPABILITIES=cuda,utility
    command: ["python3", "app.py"]
    ports:
      - "8080:5000"
    volumes:
      - ./data:/app/data  
      - ./model:/app/model